---
title: "Closest Natcoms"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

Staff at the bureau of natural and cultural resources (BNCR) want to do site visits to natural communities closest to them. Using the location of the office where BNCR is located, the closest natural community of each type will be listed.

```{r}
library(tidyverse)
```

imoprt natcom layer and near table generated in ArcGIS Pro

```{r}
natcoms <- sf::st_read('C:/Users/Spencer_C/Desktop/GDB Copy/FloridaStateParksGIS.gdb', 
                       layer = 'Natural_Communities_Statewide',
                       fid_column_name = 'oid') |>
  as_tibble() |>
  janitor:: clean_names()

near_table <- sf::st_read('C:/Users/Spencer_C/Documents/ArcGIS/Projects/Closest NatComs/Closest NatComs.gdb', 
                          layer = 'NearTable') |>
  as_tibble() |>
  janitor:: clean_names()

```

select only relevant fields and join tables based on object id (oid).

```{r clean}
nc <- natcoms |>
  select(site_name, ec_type, ec_code, dfc_type, dfc_code, acreage, oid) |>
  mutate(oid = as.integer(oid))
  

nt <- near_table |>
  select('oid' = near_fid, 'distance' = near_dist, 'rank' = near_rank)

closest_nc <- left_join(nc, nt, by = join_by(oid)) |>
  # select(-oid) |>
  group_by(ec_type) |>
  slice(which.min(distance)) |>
  mutate(distance = round(distance, 0)) |>
  select('NatCom' = ec_type, 'Park' = site_name, acreage, 'distance (mi)' = distance, everything())|>
  select(-rank)
```

export table

```{r}
closest_nc |>
  writexl::write_xlsx('C:/Users/Spencer_C/Documents/ArcGIS/Projects/Closest NatComs/Closest Natural Communities.xlsx')
```
